# Generated by Django 3.2.6 on 2021-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
