# Generated by Django 3.2.6 on 2021-08-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.CharField(max_length=100)),
                ('assignor_username', models.CharField(max_length=100)),
                ('assignee_username', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('assignee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assign_for', to=settings.AUTH_USER_MODEL)),
                ('assignor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assign_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Creator_username', models.CharField(default='', max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creator_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
