# Generated by Django 3.2.6 on 2021-08-10 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usertask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuser',
            name='assignee_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assign_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='assignee_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='assignor_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assign_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='assignor_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
