# Generated by Django 3.2.6 on 2021-08-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usertask', '0002_auto_20210810_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskuser',
            old_name='userEmail',
            new_name='assignee_Email',
        ),
    ]
